//! Build script for midi-cli-rs
//!
//! Generates version_info.rs with build metadata for --version output.

use std::fs;
use std::path::Path;
use std::process::Command;

fn main() {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest_path = Path::new(&out_dir).join("version_info.rs");

    // Read COPYRIGHT file
    let copyright = fs::read_to_string("COPYRIGHT")
        .map(|s| s.trim().to_string())
        .unwrap_or_else(|_| "Copyright (c) 2026 Michael A Wright".to_string());

    // Get version from Cargo
    let version = std::env::var("CARGO_PKG_VERSION").unwrap_or_else(|_| "0.1.0".to_string());

    // Get license from Cargo
    let license_name = std::env::var("CARGO_PKG_LICENSE").unwrap_or_else(|_| "MIT".to_string());

    // Get repository from Cargo
    let repository = std::env::var("CARGO_PKG_REPOSITORY")
        .unwrap_or_else(|_| "https://github.com/softwarewrighter/midi-cli-rs".to_string());
    let license_url = format!("{}/blob/main/LICENSE", repository);

    // Get hostname
    let hostname = Command::new("hostname")
        .output()
        .map(|output| String::from_utf8_lossy(&output.stdout).trim().to_string())
        .unwrap_or_else(|_| "unknown".to_string());

    // Get git commit SHA
    let commit_sha = Command::new("git")
        .args(["rev-parse", "HEAD"])
        .output()
        .map(|output| String::from_utf8_lossy(&output.stdout).trim().to_string())
        .unwrap_or_else(|_| "unknown".to_string());

    // Get build timestamp
    let timestamp = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_millis() as i64)
        .unwrap_or(0);

    // Generate version_info.rs
    let generated_code = format!(
        r#"// Generated by build.rs - do not edit manually

pub const VERSION: &str = "{version}";
pub const COPYRIGHT: &str = "{copyright}";
pub const LICENSE_NAME: &str = "{license_name}";
pub const LICENSE_URL: &str = "{license_url}";
pub const BUILD_HOST: &str = "{hostname}";
pub const GIT_COMMIT_SHA: &str = "{commit_sha}";
pub const BUILD_TIMESTAMP: i64 = {timestamp};
"#
    );

    fs::write(&dest_path, generated_code).expect("Failed to write version_info.rs");

    // Rerun if these files change
    println!("cargo:rerun-if-changed=COPYRIGHT");
    println!("cargo:rerun-if-changed=Cargo.toml");
}
