//! Build script for midi-cli-web
//!
//! Generates version_info.rs with build metadata for footer display.

use std::fs;
use std::path::Path;
use std::process::Command;

fn main() {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest_path = Path::new(&out_dir).join("version_info.rs");

    // Get version from parent Cargo.toml
    let version = std::env::var("CARGO_PKG_VERSION").unwrap_or_else(|_| "0.1.0".to_string());

    // Get git commit SHA
    let commit_sha = Command::new("git")
        .args(["rev-parse", "HEAD"])
        .output()
        .map(|output| String::from_utf8_lossy(&output.stdout).trim().to_string())
        .unwrap_or_else(|_| "unknown".to_string());

    let short_sha = if commit_sha.len() > 7 {
        &commit_sha[..7]
    } else {
        &commit_sha
    };

    // Get build timestamp as ISO string
    let build_time = chrono::Utc::now().to_rfc3339();

    // Generate version_info.rs
    let generated_code = format!(
        r#"// Generated by build.rs - do not edit manually

pub const VERSION: &str = "{version}";
pub const GIT_COMMIT_SHORT: &str = "{short_sha}";
pub const BUILD_TIME: &str = "{build_time}";
pub const COPYRIGHT: &str = "Copyright (c) 2026 Michael A Wright";
pub const LICENSE: &str = "MIT";
pub const REPO_URL: &str = "https://github.com/softwarewrighter/midi-cli-rs";
pub const LICENSE_URL: &str = "https://github.com/softwarewrighter/midi-cli-rs/blob/main/LICENSE";
"#
    );

    fs::write(&dest_path, generated_code).expect("Failed to write version_info.rs");

    // Rerun if git changes
    println!("cargo:rerun-if-changed=../.git/HEAD");
    println!("cargo:rerun-if-changed=../.git/refs/heads");
}
